name: CI/CD Strawberry Tracker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Instalar ferramentas de teste
        run: npm install -D vitest @vitest/ui @vue/test-utils

      - name: Executar testes
        run: npm run test -- --reporter junit --outputFile test-report.xml

      - name: Salvar relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: test-report.xml

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Build do projeto
        run: npm run build

      - name: Salvar pacote buildado
        uses: actions/upload-artifact@v4
        with:
          name: pacote-build
          path: dist/

  notify:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências Python
        run: pip install yagmail

      - name: Enviar e-mail de notificação
        env:
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: python .github/scripts/send_email.py